name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    # - name: Set up Go 1.13
    #   uses: actions/setup-go@master
    #   with:
    #     go-version: 1.13
    #   id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@master

    # - name: Get dependencies
    #   run: |
    #     go get -v -t -d ./...
    #     if [ -f Gopkg.toml ]; then
    #         curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    #         dep ensure
    #     fi

    # - name: Build
    #   run: go build -v .

    - run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }} 
    - run: docker build -t leyius/go-gin:master .
    - run: docker push leyius/go-gin:master
    - run: docker rmi leyius/go-gin:master
